### ISSUE TITLE
Errors after Fungus 3.13 update

### ISSUE THREAD

**Issue by Vaqq** [CG-Tespy/Fungus-Slot-based-Narrative-System#1]
Hello. SBSS and SBNS are both in the project and then I update Fungus with Fungus.Compatibility._v3.13.0-rc2 and get these errors:

GUID [5f81c0037bb56f542aa6a0464022285a] for asset 'Assets/[CGT] Fungus Narrative Log/Scenes/NarrativeLogTest.unity' conflicts with:
  'Assets/FungusExamples/Conversation/NarrativeEntryLogTest.unity' (current owner)
Assigning a new guid.

GUID [fde579c9edfbe7e469349e39e2a87a48] for asset 'Assets/[CGT] Fungus Narrative Log/Scripts/NarrativeLogUI.cs' conflicts with:
  'Assets/Fungus/Scripts/Components/NarrativeLogEntryUI.cs' (current owner)
Assigning a new guid.

Assets\[CGT] Fungus Narrative Log\Scripts\NarrativeLogUI.cs(4,96): error CS0234: The type or namespace name 'NarrativeLogEntryDisplay' does not exist in the namespace 'CGTUnity.Fungus.NarrativeLogSystem' (are you missing an assembly reference?)

**Comment by CG-Tespy** [comment]
Try overwriting the SBNS on your end with the one that comes with Fungus 3.13, and let me know what errors you get. If they're what I expect, then the fix will be simple :)

**Comment by Vaqq** [comment]
Hi, overwrote SBNS with Fungus_v3.13.0, got this error:

Assets\[CGT] Fungus Narrative Log\Scripts\NarrativeLogUI.cs(4,96): error CS0234: The type or namespace name 'NarrativeLogEntryDisplay' does not exist in the namespace 'CGTUnity.Fungus.NarrativeLogSystem' (are you missing an assembly reference?)

**Comment by CG-Tespy** [comment]
It seems you didn't overwrite it correctly. Delete the SBNS's folder from your project, then import the copy that Fungus 3.13 came with. That should make sure that the one you have is 3.13's, and not the one from my repo. 

Let me know what errors you then get.

**Comment by Vaqq** [comment]
Did not get any errors, when I deleted SBNS, also deleted SaveSystemExtras folder, that came with SBSS. 
All is well now, thank you for your time!

**Comment by CG-Tespy** [comment]
Glad things worked out for you :)
